#!/usr/bin/env python3
"""Apply and roll back allowlisted ``auto_safe`` memory-audit repairs.

The input is a JSON plan. Outputs are derived again from unchanged canonical
sources, generated manifest state, or a privacy-scanned snapshot candidate.
Every action carries before/after hashes, making the proposed diff a
precondition rather than an assertion made after the write.
"""

from __future__ import annotations

import argparse
import base64
import difflib
import hashlib
import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile


EXIT_OK = 0
EXIT_REFUSED = 1
EXIT_USAGE = 2
RULE_MARKER = "<!-- Generated by The Borg rule bridge. Edit the canonical .claude/rules source, not this file. -->"
COMMAND_MARKER = "<!-- Generated by The Borg command bridge. Edit the canonical .claude/commands source, not this file. -->"
SNAPSHOT_TARGET = "c4po/.claude/scheduled/state/memory-inventory.json"
COMMAND_MANIFEST_TARGET = "skills/.theborg-managed-skills.tsv"


class Refusal(Exception):
    pass


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_bytes(path: str) -> bytes:
    try:
        with open(path, "rb") as handle:
            return handle.read()
    except OSError as exc:
        raise Refusal("cannot read %s: %s" % (path, exc)) from exc


def load_json(path: str):
    try:
        return json.loads(read_bytes(path).decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise Refusal("invalid JSON in %s: %s" % (path, exc)) from exc


def safe_path(base: str, rel: str) -> str:
    if not isinstance(rel, str) or not rel or os.path.isabs(rel):
        raise Refusal("path must be a non-empty relative path: %r" % rel)
    normalized = os.path.normpath(rel)
    if normalized == ".." or normalized.startswith("../"):
        raise Refusal("path escapes its declared root: %s" % rel)
    absolute = os.path.abspath(os.path.join(base, normalized))
    if os.path.commonpath((os.path.abspath(base), absolute)) != os.path.abspath(base):
        raise Refusal("path escapes its declared root: %s" % rel)
    resolved_base = os.path.realpath(base)
    resolved_parent = os.path.realpath(os.path.dirname(absolute))
    if os.path.commonpath((resolved_base, resolved_parent)) != resolved_base:
        raise Refusal("path escapes its declared root through a symlink: %s" % rel)
    if os.path.islink(absolute):
        raise Refusal("refusing symlink target: %s" % rel)
    return absolute


def roots(args):
    root = os.path.abspath(args.root or os.path.join(os.path.dirname(__file__), ".."))
    codex = os.path.abspath(args.codex_home or os.environ.get("CODEX_HOME")
                            or os.path.join(os.path.expanduser("~"), ".codex"))
    return {"borg_root": root, "codex_home": codex}


def import_inventory_tool(root: str):
    path = os.path.join(root, ".bin", "build-memory-inventory.py")
    spec = importlib.util.spec_from_file_location("build_memory_inventory_apply", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def registry_index(root: str):
    bmi = import_inventory_tool(root)
    path = os.path.join(root, "MEMORY-INVENTORY.yaml")
    doc = bmi.load_yaml(read_bytes(path).decode("utf-8"), "MEMORY-INVENTORY.yaml")
    defaults = doc.get("defaults", {})
    records = {}
    for artifact_id, record in doc.get("artifacts", {}).items():
        merged = bmi.apply_defaults(record, defaults)
        key = (merged.get("path_root", "borg_root"), merged.get("path"))
        if key in records:
            raise Refusal("duplicate public inventory target: %s:%s" % key)
        records[key] = (artifact_id, merged)
    return records


def records_by_id(records):
    return {artifact_id: (path_root, path, record)
            for (path_root, path), (artifact_id, record) in records.items()}


def frontmatter(source: str):
    lines = source.splitlines()
    if not lines or lines[0] != "---":
        raise Refusal("canonical source is missing YAML frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise Refusal("canonical source has unterminated YAML frontmatter") from exc
    values = {}
    for line in lines[1:end]:
        match = re.match(r"^([a-zA-Z0-9_-]+):\s*(.*)$", line)
        if match:
            values.setdefault(match.group(1), []).append(match.group(2))
    return values, "\n".join(lines[end + 1:]) + ("\n" if source.endswith("\n") else "")


def render_rule(source_rel: str, target_rel: str, source: bytes) -> bytes:
    match = re.fullmatch(r"(?:(.+)/)?\.claude/rules/([^/]+)\.md", source_rel)
    if not match:
        raise Refusal("rule canonical source has the wrong path shape: %s" % source_rel)
    scope, filename = match.group(1) or "", match.group(2) + ".md"
    values, _ = frontmatter(source.decode("utf-8"))
    if len(values.get("name", [])) != 1 or len(values.get("description", [])) != 1:
        raise Refusal("rule source needs one name and one description")
    name, description = values["name"][0], values["description"][0]
    suffix = ".local" if source_rel.endswith(".local.md") else ""
    expected = os.path.join(scope, ".agents/skills", name + suffix, "SKILL.md")
    if os.path.normpath(target_rel) != os.path.normpath(expected):
        raise Refusal("rule bridge target does not match its canonical source")
    text = """---
name: %s
description: %s
---

%s

Read `../../../.claude/rules/%s` — the path is relative to this SKILL.md — and
follow it in full. That file is the canonical rule. Claude Code loads it
automatically from `.claude/rules/`; this skill exists only so Codex reaches the
same text from the same directory scope.
""" % (name, description, RULE_MARKER, filename)
    return text.encode("utf-8")


def render_command(target_rel: str, source: bytes) -> bytes:
    values, body = frontmatter(source.decode("utf-8"))
    if len(values.get("description", [])) != 1:
        raise Refusal("command source needs exactly one description")
    match = re.fullmatch(r"skills/([a-z0-9-]+)/SKILL\.md", target_rel)
    if not match:
        raise Refusal("command bridge target has the wrong path shape: %s" % target_rel)
    skill = match.group(1)
    text = """---
name: %s
description: %s
---

%s

Treat the user's request accompanying an explicit `$%s` mention as this workflow's arguments.
Where the instructions below refer to `$ARGUMENTS`, use that accompanying request (or the full triggering request when invoked implicitly). Claude Code-only frontmatter does not apply; use the current Codex model.

%s""" % (skill, values["description"][0], COMMAND_MARKER, skill, body)
    return text.encode("utf-8")


def render_command_manifest(root_map, records, before: bytes) -> bytes:
    try:
        lines = before.decode("utf-8").splitlines()
    except UnicodeDecodeError as exc:
        raise Refusal("command bridge manifest must be UTF-8") from exc
    expected = {}
    by_id = records_by_id(records)
    for (path_root, path), (artifact_id, record) in records.items():
        if record.get("type") != "generated_command_bridge":
            continue
        if (record.get("canonicality") != "generated" or record.get("visibility") != "public"
                or record.get("remediation_policy") != "auto_safe"):
            continue
        if path_root != "codex_home":
            raise Refusal("command bridge %s is outside codex_home" % artifact_id)
        match = re.fullmatch(r"skills/([a-z0-9-]+)/SKILL\.md", path)
        canonical = by_id.get(record.get("canonical_ref"))
        if not match or not canonical or canonical[0] != "borg_root":
            raise Refusal("command bridge %s has an invalid generated relationship" % artifact_id)
        source_abs = safe_path(root_map["borg_root"], canonical[1])
        generated = render_command(path, read_bytes(source_abs))
        expected[match.group(1)] = (source_abs, sha(generated))
    seen, output = set(), []
    for line in lines:
        fields = line.split("\t")
        if len(fields) != 3:
            raise Refusal("command bridge manifest has a malformed row")
        skill = fields[0]
        if skill in expected:
            if skill in seen:
                raise Refusal("command bridge manifest has duplicate skill %s" % skill)
            seen.add(skill)
            source_abs, expected_hash = expected[skill]
            line = "\t".join((skill, source_abs, expected_hash))
        output.append(line)
    missing = sorted(set(expected) - seen)
    if missing:
        raise Refusal("command bridge manifest is missing managed entries: %s"
                      % ", ".join(missing))
    return (("\n".join(output) + "\n") if output else "").encode("utf-8")


def require_bridge_policy(records, action, expected_type: str):
    target = action["target"]
    source = action["source"]
    found = records.get((target["path_root"], target["path"]))
    if not found:
        raise Refusal("generated target has no public inventory record: %s" % target["path"])
    artifact_id, record = found
    if (record.get("type") != expected_type or record.get("canonicality") != "generated"
            or record.get("visibility") != "public"
            or record.get("remediation_policy") != "auto_safe"):
        raise Refusal("inventory record %s is not an auto_safe public generated %s"
                      % (artifact_id, expected_type))
    canonical = records.get((source["path_root"], source["path"]))
    if not canonical or record.get("canonical_ref") != canonical[0]:
        raise Refusal("generated target's canonical_ref does not identify the supplied source")


def privacy_scan(root: str, candidate: str):
    scanner = os.path.join(root, ".bin", "tests", "audit-privacy-scan.py")
    result = subprocess.run([sys.executable, scanner, "--profile", "snapshot",
                             "--root", root, candidate], stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True)
    if result.returncode:
        raise Refusal("candidate snapshot failed the privacy scan")


def derive(action, root_map, records):
    if action.get("tier") != "auto_safe":
        raise Refusal("action %r is not tier auto_safe" % action.get("id"))
    if set(action) - {"id", "tier", "kind", "target", "source", "candidate"}:
        raise Refusal("action %r has unsupported fields" % action.get("id"))
    target = action.get("target")
    if not isinstance(target, dict) or set(target) != {"path_root", "path", "before_sha256", "after_sha256"}:
        raise Refusal("action %r has an invalid target" % action.get("id"))
    if target["path_root"] not in root_map:
        raise Refusal("action %r uses an unsupported target root" % action.get("id"))
    target_abs = safe_path(root_map[target["path_root"]], target["path"])
    before = read_bytes(target_abs)
    kind = action.get("kind")

    if kind in ("generated_rule_bridge", "generated_command_bridge"):
        source = action.get("source")
        if not isinstance(source, dict) or set(source) != {"path_root", "path", "sha256"}:
            raise Refusal("bridge action %r has an invalid source" % action.get("id"))
        if source["path_root"] != "borg_root":
            raise Refusal("canonical bridge source must be in borg_root")
        source_abs = safe_path(root_map["borg_root"], source["path"])
        source_data = read_bytes(source_abs)
        if sha(source_data) != source["sha256"]:
            raise Refusal("canonical source changed for action %r" % action.get("id"))
        require_bridge_policy(records, action, kind)
        if kind == "generated_rule_bridge":
            if target["path_root"] != "borg_root":
                raise Refusal("rule bridge must stay in borg_root")
            after = render_rule(source["path"], target["path"], source_data)
        else:
            if target["path_root"] != "codex_home":
                raise Refusal("command bridge must stay in codex_home")
            after = render_command(target["path"], source_data)
    elif kind == "generated_command_manifest":
        if (target["path_root"], target["path"]) != ("codex_home", COMMAND_MANIFEST_TARGET):
            raise Refusal("command manifest action has a non-allowlisted target")
        if "source" in action or "candidate" in action:
            raise Refusal("command manifest is derived from the public registry")
        after = render_command_manifest(root_map, records, before)
    elif kind == "generated_snapshot":
        if target["path_root"] != "borg_root" or target["path"] != SNAPSHOT_TARGET:
            raise Refusal("snapshot action may target only %s" % SNAPSHOT_TARGET)
        if "source" in action:
            raise Refusal("snapshot action must use candidate, not source")
        candidate = action.get("candidate")
        if not isinstance(candidate, dict) or set(candidate) != {"path_root", "path", "sha256"}:
            raise Refusal("snapshot action has an invalid candidate")
        if candidate["path_root"] != "borg_root" or not os.path.normpath(candidate["path"]).startswith("tmp/"):
            raise Refusal("snapshot candidate must be under borg_root/tmp")
        candidate_abs = safe_path(root_map["borg_root"], candidate["path"])
        after = read_bytes(candidate_abs)
        if sha(after) != candidate["sha256"]:
            raise Refusal("snapshot candidate changed")
        try:
            json.loads(after.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise Refusal("snapshot candidate is not valid JSON") from exc
        privacy_scan(root_map["borg_root"], candidate_abs)
    else:
        raise Refusal("unsupported auto_safe action kind: %r" % kind)

    if sha(after) != target["after_sha256"]:
        raise Refusal("derived output does not match proposed after_sha256 for %r"
                      % action.get("id"))
    current = sha(before)
    if current not in (target["before_sha256"], target["after_sha256"]):
        raise Refusal("target changed outside the plan for action %r" % action.get("id"))
    return target_abs, before, after


def atomic_write(path: str, data: bytes):
    directory = os.path.dirname(path)
    mode = os.stat(path).st_mode & 0o777 if os.path.exists(path) else 0o600
    fd, temporary = tempfile.mkstemp(prefix=".memory-audit-", dir=directory)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def diff_text(label: str, before: bytes, after: bytes) -> str:
    try:
        left, right = before.decode("utf-8").splitlines(True), after.decode("utf-8").splitlines(True)
    except UnicodeDecodeError as exc:
        raise Refusal("auto_safe outputs must be UTF-8 text") from exc
    return "".join(difflib.unified_diff(left, right, fromfile=label + ".before",
                                        tofile=label + ".after"))


def validate_plan(plan):
    if not isinstance(plan, dict) or set(plan) != {"version", "actions"} or plan["version"] != 1:
        raise Refusal("plan must contain exactly version: 1 and actions")
    if not isinstance(plan["actions"], list):
        raise Refusal("plan actions must be a list")
    ids = [a.get("id") for a in plan["actions"] if isinstance(a, dict)]
    if len(ids) != len(plan["actions"]) or any(not isinstance(i, str) or not i for i in ids):
        raise Refusal("every action needs a non-empty string id")
    if len(set(ids)) != len(ids):
        raise Refusal("action ids must be unique")
    kinds = [action.get("kind") for action in plan["actions"]]
    manifest_positions = [index for index, kind in enumerate(kinds)
                          if kind == "generated_command_manifest"]
    command_positions = [index for index, kind in enumerate(kinds)
                         if kind == "generated_command_bridge"]
    if len(manifest_positions) > 1:
        raise Refusal("a plan may contain at most one command manifest action")
    if command_positions and not manifest_positions:
        raise Refusal("command bridge repairs require the managed-manifest action")
    if command_positions and manifest_positions[0] < max(command_positions):
        raise Refusal("the managed-manifest action must follow command bridge repairs")


def receipt_path(root: str, path: str) -> str:
    absolute = os.path.abspath(path)
    work_root = os.path.join(root, "tmp")
    if os.path.commonpath((work_root, absolute)) != work_root:
        raise Refusal("receipt must stay under borg_root/tmp")
    parent = os.path.dirname(absolute)
    if not os.path.isdir(parent):
        raise Refusal("plan/receipt parent directory must already exist")
    if os.path.commonpath((os.path.realpath(work_root), os.path.realpath(parent))) != os.path.realpath(work_root):
        raise Refusal("plan/receipt escapes borg_root/tmp through a symlink")
    if os.path.islink(absolute):
        raise Refusal("refusing symlink plan/receipt target")
    return absolute


def cmd_plan(args):
    root_map = roots(args)
    records = registry_index(root_map["borg_root"])
    by_id = records_by_id(records)
    actions = []
    for (target_root, target_rel), (artifact_id, record) in sorted(records.items()):
        kind = record.get("type")
        if kind not in ("generated_rule_bridge", "generated_command_bridge"):
            continue
        if (record.get("canonicality") != "generated" or record.get("visibility") != "public"
                or record.get("remediation_policy") != "auto_safe"):
            continue
        canonical = by_id.get(record.get("canonical_ref"))
        if not canonical:
            raise Refusal("generated record %s has no resolvable canonical_ref" % artifact_id)
        source_root, source_rel, _source_record = canonical
        if source_root != "borg_root":
            raise Refusal("generated record %s has a canonical source outside borg_root" % artifact_id)
        source_abs = safe_path(root_map[source_root], source_rel)
        target_abs = safe_path(root_map[target_root], target_rel)
        source_data, before = read_bytes(source_abs), read_bytes(target_abs)
        after = (render_rule(source_rel, target_rel, source_data)
                 if kind == "generated_rule_bridge"
                 else render_command(target_rel, source_data))
        if before == after:
            continue
        actions.append({
            "id": "repair-" + artifact_id,
            "tier": "auto_safe", "kind": kind,
            "target": {"path_root": target_root, "path": target_rel,
                       "before_sha256": sha(before), "after_sha256": sha(after)},
            "source": {"path_root": source_root, "path": source_rel,
                       "sha256": sha(source_data)},
        })
    manifest_abs = safe_path(root_map["codex_home"], COMMAND_MANIFEST_TARGET)
    manifest_before = read_bytes(manifest_abs)
    manifest_after = render_command_manifest(root_map, records, manifest_before)
    if manifest_before != manifest_after:
        actions.append({
            "id": "repair-command-bridge-manifest",
            "tier": "auto_safe", "kind": "generated_command_manifest",
            "target": {"path_root": "codex_home", "path": COMMAND_MANIFEST_TARGET,
                       "before_sha256": sha(manifest_before),
                       "after_sha256": sha(manifest_after)},
        })
    if args.candidate_snapshot:
        candidate_abs = safe_path(root_map["borg_root"], args.candidate_snapshot)
        if not os.path.normpath(args.candidate_snapshot).startswith("tmp/"):
            raise Refusal("snapshot candidate must be under borg_root/tmp")
        candidate = read_bytes(candidate_abs)
        try:
            json.loads(candidate.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise Refusal("snapshot candidate is not valid JSON") from exc
        privacy_scan(root_map["borg_root"], candidate_abs)
        target_abs = safe_path(root_map["borg_root"], SNAPSHOT_TARGET)
        before = read_bytes(target_abs)
        if before != candidate:
            actions.append({
                "id": "refresh-memory-inventory-snapshot",
                "tier": "auto_safe", "kind": "generated_snapshot",
                "target": {"path_root": "borg_root", "path": SNAPSHOT_TARGET,
                           "before_sha256": sha(before), "after_sha256": sha(candidate)},
                "candidate": {"path_root": "borg_root", "path": args.candidate_snapshot,
                              "sha256": sha(candidate)},
            })
    output = receipt_path(root_map["borg_root"], args.output)
    os.makedirs(os.path.dirname(output), exist_ok=True)
    atomic_write(output, (json.dumps({"version": 1, "actions": actions},
                                     indent=2, sort_keys=True) + "\n").encode("utf-8"))
    print("Planned %d auto_safe action(s): %s" % (len(actions), output))
    return EXIT_OK


def cmd_apply(args):
    root_map = roots(args)
    receipt_file = receipt_path(root_map["borg_root"], args.receipt)
    plan = load_json(args.plan)
    validate_plan(plan)
    records = registry_index(root_map["borg_root"])
    if not plan["actions"]:
        print("Nothing to apply: the auto_safe plan is empty.")
        return EXIT_OK
    derived = []
    targets = set()
    for action in plan["actions"]:
        target, before, after = derive(action, root_map, records)
        if target in targets:
            raise Refusal("two actions target the same file")
        targets.add(target)
        derived.append((action, target, before, after))
    states = [sha(before) == action["target"]["after_sha256"]
              for action, _target, before, _after in derived]
    if any(states) and not all(states):
        raise Refusal("plan is partially applied; roll it back before retrying")
    if all(states):
        print("Nothing to apply: every target already matches the proposed output.")
        return EXIT_OK

    receipt = {"version": 1, "status": "applied", "actions": []}
    for action, _target, before, after in derived:
        print(diff_text(action["id"], before, after), end="")
        receipt["actions"].append({
            "id": action["id"], "kind": action["kind"], "target": action["target"],
            "applied_sha256": sha(after),
            "original_sha256": sha(before),
            "original_base64": base64.b64encode(before).decode("ascii"),
        })
    receipt_bytes = (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode("utf-8")
    if os.path.exists(receipt_file):
        raise Refusal("receipt already exists: %s" % receipt_file)
    os.makedirs(os.path.dirname(receipt_file), exist_ok=True)
    atomic_write(receipt_file, receipt_bytes)
    written = []
    try:
        for _action, target, _before, after in derived:
            atomic_write(target, after)
            written.append(target)
        for _action, target, _before, after in derived:
            if read_bytes(target) != after:
                raise Refusal("post-write verification failed: %s" % target)
    except Exception:
        for _action, target, before, _after in reversed(derived):
            if target in written:
                atomic_write(target, before)
        receipt["status"] = "rolled_back"
        receipt["failure"] = "apply failed; completed writes were restored"
        atomic_write(receipt_file,
                     (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode("utf-8"))
        raise
    print("Applied %d auto_safe action(s); rollback receipt: %s" %
          (len(derived), receipt_file))
    return EXIT_OK


def cmd_rollback(args):
    root_map = roots(args)
    receipt_file = receipt_path(root_map["borg_root"], args.receipt)
    receipt = load_json(receipt_file)
    records = registry_index(root_map["borg_root"])
    if not isinstance(receipt, dict) or receipt.get("version") != 1 or not isinstance(receipt.get("actions"), list):
        raise Refusal("invalid rollback receipt")
    if receipt.get("status") == "rolled_back":
        print("Nothing to roll back: receipt is already rolled_back.")
        return EXIT_OK
    if receipt.get("status") != "applied":
        raise Refusal("rollback receipt is not in applied state")
    restores = []
    for item in receipt["actions"]:
        target = item.get("target", {})
        kind = item.get("kind")
        if target.get("path_root") not in root_map:
            raise Refusal("receipt uses an unsupported target root")
        if kind == "generated_snapshot":
            if (target.get("path_root"), target.get("path")) != ("borg_root", SNAPSHOT_TARGET):
                raise Refusal("receipt snapshot target is not allowlisted")
        elif kind in ("generated_rule_bridge", "generated_command_bridge"):
            found = records.get((target.get("path_root"), target.get("path")))
            if not found:
                raise Refusal("receipt bridge target has no inventory record")
            record = found[1]
            if (record.get("type") != kind or record.get("canonicality") != "generated"
                    or record.get("visibility") != "public"
                    or record.get("remediation_policy") != "auto_safe"):
                raise Refusal("receipt bridge target is not auto_safe")
        elif kind == "generated_command_manifest":
            if (target.get("path_root"), target.get("path")) != (
                    "codex_home", COMMAND_MANIFEST_TARGET):
                raise Refusal("receipt command manifest target is not allowlisted")
        else:
            raise Refusal("receipt contains an unsupported action kind")
        absolute = safe_path(root_map[target["path_root"]], target.get("path"))
        current = read_bytes(absolute)
        original = base64.b64decode(item.get("original_base64", ""), validate=True)
        if sha(original) != item.get("original_sha256") or sha(original) != target.get("before_sha256"):
            raise Refusal("receipt original does not match the applied plan")
        if sha(current) == sha(original):
            restores.append((absolute, original, False))
        elif sha(current) == item.get("applied_sha256"):
            restores.append((absolute, original, True))
        else:
            raise Refusal("target changed after apply; refusing rollback: %s" % target.get("path"))
    for absolute, original, needed in restores:
        if needed:
            atomic_write(absolute, original)
    receipt["status"] = "rolled_back"
    atomic_write(receipt_file,
                 (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode("utf-8"))
    print("Rolled back %d auto_safe action(s)." % sum(1 for _a, _o, needed in restores if needed))
    return EXIT_OK


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", help="workspace root (default: parent of .bin)")
    parser.add_argument("--codex-home", help="Codex home for command bridges")
    sub = parser.add_subparsers(dest="command", required=True)
    plan_parser = sub.add_parser("plan", help="derive an exact plan from owned generators")
    plan_parser.add_argument("--candidate-snapshot",
                             help="workspace-relative candidate under tmp/ to include")
    plan_parser.add_argument("--output", required=True,
                             help="plan path under the workspace tmp/ directory")
    plan_parser.set_defaults(func=cmd_plan)
    apply_parser = sub.add_parser("apply", help="apply an allowlisted plan transactionally")
    apply_parser.add_argument("--plan", required=True)
    apply_parser.add_argument("--receipt", required=True)
    apply_parser.set_defaults(func=cmd_apply)
    rollback_parser = sub.add_parser("rollback", help="restore targets from an apply receipt")
    rollback_parser.add_argument("--receipt", required=True)
    rollback_parser.set_defaults(func=cmd_rollback)
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (Refusal, OSError, ValueError) as exc:
        print("REFUSED: %s" % exc, file=sys.stderr)
        return EXIT_REFUSED


if __name__ == "__main__":
    sys.exit(main())
