#!/usr/bin/env bash
# Expose Borg Claude Code commands to Codex as skills.
# .claude/commands/*.md remains canonical; generated SKILL.md files adapt its frontmatter.
set -euo pipefail

MODE="sync"
case "${1:-}" in
  --check) MODE="check" ;;
  --print) MODE="print" ;;
  "") ;;
  *) echo "usage: $(basename "$0") [--check|--print]" >&2; exit 64 ;;
esac

BORG_ROOT="${BORG_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
CODEX_ROOT="${CODEX_HOME:-$HOME/.codex}"
SKILLS_DIR="${BORG_CODEX_SKILLS_DIR:-$CODEX_ROOT/skills}"
MANIFEST="$SKILLS_DIR/.theborg-managed-skills.tsv"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/theborg-skills.XXXXXX")"
trap 'rm -rf "$WORK_DIR"' EXIT

INVENTORY="$WORK_DIR/inventory.tsv"
PLAN="$WORK_DIR/plan.tsv"
GENERATED_DIR="$WORK_DIR/generated"
: > "$INVENTORY"
: > "$PLAN"
mkdir -p "$GENERATED_DIR"

while IFS= read -r source; do
  rel="${source#"$BORG_ROOT"/}"
  case "$rel" in
    .claude/commands/*) scope="workspace" ;;
    */.claude/commands/*) scope="${rel%%/.claude/commands/*}" ;;
    *) continue ;;
  esac

  name="$(basename "$source" .md)"
  case "$name" in
    ""|*[!a-z0-9-]*)
      echo "unsupported skill name from command filename: $source" >&2
      exit 1
      ;;
  esac
  safe_scope="$(printf '%s' "$scope" | tr '/ _' '---' | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')"
  printf '%s\t%s\t%s\n' "$name" "$safe_scope" "$source" >> "$INVENTORY"
# The .claude/worktrees prune below matters: that directory holds ephemeral git
# worktrees created by agent sessions (Claude Code's EnterWorktree, the
# background-task chips). Each is a full checkout, so without the prune the scan
# finds a second copy of every command in the tree. The duplicates generate junk
# claude-worktrees-NAME-* skills and, worse, colliding with the real commands
# demotes those to scope-prefixed workspace-* names -- so the backlog skill
# silently becomes workspace-backlog for as long as the worktree exists.
# Observed 2026-08-15, when a concurrent session's worktree took the bridge from
# 20 skills to 39. Keep comments OUT of the process substitution below: bash
# parses backticks inside it even in a comment, and a stray pair fails the whole
# command at expansion time while `bash -n` still passes.
done < <(
  find "$BORG_ROOT" \
    \( -path "$BORG_ROOT/.git" -o -path "$BORG_ROOT/bernard" \
       -o -path '*/.claude/worktrees' \
       -o -path '*/.git' -o -path '*/node_modules' -o -path '*/dist' -o -path '*/build' \) -prune \
    -o -type f -path '*/.claude/commands/*.md' -print | LC_ALL=C sort
)

while IFS=$'\t' read -r name scope source; do
  count="$(awk -F '\t' -v wanted="$name" '$1 == wanted { count++ } END { print count + 0 }' "$INVENTORY")"
  if (( count > 1 )); then
    skill_name="$scope-$name"
  else
    skill_name="$name"
  fi
  printf '%s\t%s\n' "$skill_name" "$source" >> "$PLAN"
done < "$INVENTORY"

LC_ALL=C sort -o "$PLAN" "$PLAN"
duplicates="$(cut -f1 "$PLAN" | uniq -d)"
if [[ -n "$duplicates" ]]; then
  echo "skill names still collide after scope-prefixing:" >&2
  echo "$duplicates" >&2
  exit 1
fi

generate_skill() {
  local skill_name="$1" source="$2" output="$3"
  local description_line body_start

  if [[ "$(sed -n '1p' "$source")" != "---" ]]; then
    echo "command is missing YAML frontmatter: $source" >&2
    return 1
  fi
  body_start="$(awk 'NR > 1 && $0 == "---" { print NR + 1; exit }' "$source")"
  if [[ -z "$body_start" ]]; then
    echo "command has unterminated YAML frontmatter: $source" >&2
    return 1
  fi
  description_line="$(sed -n "2,$((body_start - 2))p" "$source" | awk '/^description:[[:space:]]*/ { print; count++ } END { if (count != 1) exit 1 }')" || {
    echo "command must have exactly one single-line description: $source" >&2
    return 1
  }

  {
    printf '%s\n' '---'
    printf 'name: %s\n' "$skill_name"
    printf '%s\n' "$description_line"
    printf '%s\n\n' '---'
    printf '%s\n\n' '<!-- Generated by The Borg command bridge. Edit the canonical .claude/commands source, not this file. -->'
    printf '%s\n' "Treat the user's request accompanying an explicit \`\$$skill_name\` mention as this workflow's arguments."
    printf '%s\n\n' 'Where the instructions below refer to `$ARGUMENTS`, use that accompanying request (or the full triggering request when invoked implicitly). Claude Code-only frontmatter does not apply; use the current Codex model.'
    sed -n "${body_start},\$p" "$source"
  } > "$output"
}

while IFS=$'\t' read -r skill_name source; do
  generate_skill "$skill_name" "$source" "$GENERATED_DIR/$skill_name.md"
done < "$PLAN"

if [[ "$MODE" == "print" ]]; then
  while IFS=$'\t' read -r skill_name source; do
    printf '$%-28s %s\n' "$skill_name" "${source#"$BORG_ROOT"/}"
  done < "$PLAN"
  exit 0
fi

managed_record() {
  local skill_name="$1"
  [[ -f "$MANIFEST" ]] || return 1
  awk -F '\t' -v wanted="$skill_name" '$1 == wanted { print $2 "\t" $3; found=1; exit } END { if (!found) exit 1 }' "$MANIFEST"
}

file_hash() {
  shasum -a 256 "$1" | awk '{ print $1 }'
}

errors=0
while IFS=$'\t' read -r skill_name source; do
  dest_dir="$SKILLS_DIR/$skill_name"
  dest="$dest_dir/SKILL.md"
  generated="$GENERATED_DIR/$skill_name.md"
  record="$(managed_record "$skill_name" 2>/dev/null || true)"
  old_source="${record%%$'\t'*}"
  old_hash="${record#*$'\t'}"
  [[ "$record" == *$'\t'* ]] || { old_source=""; old_hash=""; }

  if [[ -d "$dest_dir" && ! -L "$dest_dir" && -f "$dest" && -n "$old_source" ]]; then
    current_hash="$(file_hash "$dest")"
    expected_hash="$(file_hash "$generated")"
    if [[ "$current_hash" == "$expected_hash" && "$old_source" == "$source" && "$old_hash" == "$current_hash" ]]; then
      continue
    fi
    if [[ "$current_hash" == "$old_hash" && "$MODE" == "sync" ]]; then
      continue
    fi
    echo "conflict or manifest drift: $dest" >&2
    errors=$((errors + 1))
  elif [[ -e "$dest_dir" || -L "$dest_dir" ]]; then
    echo "conflict: $dest_dir exists and is not a managed skill directory" >&2
    errors=$((errors + 1))
  elif [[ "$MODE" != "sync" ]]; then
    echo "missing: $dest" >&2
    errors=$((errors + 1))
  fi
done < "$PLAN"

if [[ -f "$MANIFEST" ]]; then
  while IFS=$'\t' read -r old_name old_source old_hash; do
    if ! awk -F '\t' -v wanted="$old_name" '$1 == wanted { found=1 } END { exit !found }' "$PLAN"; then
      dest_dir="$SKILLS_DIR/$old_name"
      dest="$dest_dir/SKILL.md"
      if [[ -d "$dest_dir" && ! -L "$dest_dir" && -f "$dest" && "$(file_hash "$dest")" == "$old_hash" ]]; then
        if [[ "$MODE" != "sync" ]]; then
          echo "stale: $dest (source was $old_source)" >&2
          errors=$((errors + 1))
        fi
      elif [[ -e "$dest_dir" || -L "$dest_dir" ]]; then
        echo "stale manifest entry is no longer safely managed: $dest_dir" >&2
        errors=$((errors + 1))
      fi
    fi
  done < "$MANIFEST"
fi

(( errors == 0 )) || exit 1
[[ "$MODE" == "check" ]] && { echo "Codex skill bridge is current ($(wc -l < "$PLAN" | tr -d ' ') skills)."; exit 0; }

mkdir -p "$SKILLS_DIR"

if [[ -f "$MANIFEST" ]]; then
  while IFS=$'\t' read -r old_name old_source old_hash; do
    if ! awk -F '\t' -v wanted="$old_name" '$1 == wanted { found=1 } END { exit !found }' "$PLAN"; then
      dest_dir="$SKILLS_DIR/$old_name"
      dest="$dest_dir/SKILL.md"
      if [[ -d "$dest_dir" && ! -L "$dest_dir" && -f "$dest" && "$(file_hash "$dest")" == "$old_hash" ]]; then
        rm "$dest"
        rmdir "$dest_dir" 2>/dev/null || true
      fi
    fi
  done < "$MANIFEST"
fi

NEW_MANIFEST="$WORK_DIR/manifest.tsv"
: > "$NEW_MANIFEST"
while IFS=$'\t' read -r skill_name source; do
  dest_dir="$SKILLS_DIR/$skill_name"
  dest="$dest_dir/SKILL.md"
  generated="$GENERATED_DIR/$skill_name.md"
  mkdir -p "$dest_dir"
  cp "$generated" "$dest.tmp"
  mv "$dest.tmp" "$dest"
  printf '%s\t%s\t%s\n' "$skill_name" "$source" "$(file_hash "$dest")" >> "$NEW_MANIFEST"
done < "$PLAN"
cp "$NEW_MANIFEST" "$MANIFEST.tmp"
mv "$MANIFEST.tmp" "$MANIFEST"

echo "Synced $(wc -l < "$PLAN" | tr -d ' ') Borg commands as skills in $SKILLS_DIR. Invoke one as \$<name> (or choose it with /skills)."
