#!/usr/bin/env bash
# Expose Borg scoped rules to Codex as skills.
# .claude/rules/*.md remains canonical; each generated SKILL.md is a stub that
# points Codex back at that file, so the rule text itself is never duplicated.
#
# Claude Code loads .claude/rules/ directly. Codex has no equivalent loader, but it
# scans .agents/skills from the working directory up to the repository root, which
# reproduces the same directory scoping. Symlinks do NOT work here: Codex 0.147.0
# follows a symlinked skill *folder* but silently ignores a folder whose SKILL.md is
# a symlink (verified with `codex debug prompt-input` on 2026-08-15), which is why
# this generates stubs instead. See the "Scoped rules" section of LINT.md.
set -euo pipefail

MODE="sync"
case "${1:-}" in
  --check) MODE="check" ;;
  --print) MODE="print" ;;
  "") ;;
  *) echo "usage: $(basename "$0") [--check|--print]" >&2; exit 64 ;;
esac

BORG_ROOT="${BORG_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
MARKER="<!-- Generated by The Borg rule bridge. Edit the canonical .claude/rules source, not this file. -->"
PROBLEMS=0

fail() { printf '%s\n' "$1" >&2; PROBLEMS=$((PROBLEMS + 1)); }

frontmatter_value() {
  # $1 file, $2 key -- single-line value from the leading --- block
  awk -v key="$2" '
    NR == 1 && $0 != "---" { exit }
    NR > 1 && $0 == "---" { exit }
    NR > 1 && index($0, key ": ") == 1 { print substr($0, length(key) + 3); exit }
  ' "$1"
}

render_stub() {
  # $1 name, $2 description, $3 rule filename
  cat <<EOF
---
name: $1
description: $2
---

$MARKER

Read \`../../../.claude/rules/$3\` — the path is relative to this SKILL.md — and
follow it in full. That file is the canonical rule. Claude Code loads it
automatically from \`.claude/rules/\`; this skill exists only so Codex reaches the
same text from the same directory scope.
EOF
}

# The worktree prune matters for the same reason it does in sync-codex-prompts.sh:
# .claude/worktrees holds ephemeral full checkouts, so without it every rule is
# found twice and each phantom copy generates a skill in a directory that is about
# to disappear.
PRUNE=(
  \( -path "$BORG_ROOT/.git" -o -path "$BORG_ROOT/bernard"
     -o -path '*/.claude/worktrees'
     -o -path '*/.git' -o -path '*/node_modules' -o -path '*/dist' -o -path '*/build' \)
  -prune
)

EXPECTED=""

while IFS= read -r rules_dir; do
  scope="${rules_dir%/.claude/rules}"
  rel_scope="${scope#"$BORG_ROOT"/}"
  [ "$rel_scope" = "$scope" ] && rel_scope="."

  for rule in "$rules_dir"/*.md; do
    [ -e "$rule" ] || continue
    filename="$(basename "$rule")"
    base="${filename%.md}"
    name="$(frontmatter_value "$rule" name)"
    desc="$(frontmatter_value "$rule" description)"

    if [ -z "$name" ] || [ -z "$desc" ]; then
      fail "$rel_scope/.claude/rules/$filename: needs both 'name:' and 'description:' frontmatter (Codex keys skills on them)"
      continue
    fi

    # A gitignored *.local.md rule bridges into a .local-suffixed directory, which
    # the root .gitignore excludes -- otherwise its stub would leak machine details.
    case "$base" in
      *.local) dir_name="$name.local"; expected_name="${base%.local}" ;;
      *)       dir_name="$name";       expected_name="$base" ;;
    esac
    if [ "$name" != "$expected_name" ]; then
      fail "$rel_scope/.claude/rules/$filename: name '$name' does not match its filename"
      continue
    fi

    skill="$scope/.agents/skills/$dir_name/SKILL.md"
    rel_skill="$rel_scope/.agents/skills/$dir_name/SKILL.md"
    EXPECTED="$EXPECTED$skill"$'\n'

    case "$MODE" in
      print)
        printf '===== %s\n' "$rel_skill"
        render_stub "$name" "$desc" "$filename"
        ;;
      check)
        if [ ! -f "$skill" ]; then
          fail "$rel_skill: missing -- run .bin/sync-codex-rule-skills.sh"
        elif ! render_stub "$name" "$desc" "$filename" | diff -q - "$skill" >/dev/null; then
          fail "$rel_skill: stale -- run .bin/sync-codex-rule-skills.sh"
        fi
        ;;
      sync)
        if [ -f "$skill" ] && ! grep -qF "$MARKER" "$skill"; then
          fail "$rel_skill: exists and was not generated by this bridge -- refusing to overwrite"
          continue
        fi
        mkdir -p "$(dirname "$skill")"
        render_stub "$name" "$desc" "$filename" > "$skill"
        printf '%s\n' "$rel_skill"
        ;;
    esac
  done
done < <(find "$BORG_ROOT" "${PRUNE[@]}" -o -type d -path '*/.claude/rules' -print)

# Orphans: a generated stub whose rule was renamed or deleted. Only ever touch our
# own output -- anything without the marker is someone else's skill.
while IFS= read -r skill; do
  [ -n "$skill" ] || continue
  case "$EXPECTED" in *"$skill"$'\n'*) continue ;; esac
  rel_skill="${skill#"$BORG_ROOT"/}"
  if ! grep -qF "$MARKER" "$skill" 2>/dev/null; then
    continue
  fi
  case "$MODE" in
    sync)
      rm -rf "$(dirname "$skill")"
      printf 'removed orphan %s\n' "$rel_skill"
      ;;
    *)
      fail "$rel_skill: orphaned -- its rule was renamed or deleted"
      ;;
  esac
done < <(find "$BORG_ROOT" "${PRUNE[@]}" -o -path '*/.agents/skills/*/SKILL.md' -print)

if [ "$PROBLEMS" -ne 0 ]; then
  printf '%s problem(s) in the Codex rule-skill bridge\n' "$PROBLEMS" >&2
  exit 1
fi

[ "$MODE" = "check" ] && printf 'Codex rule-skill bridge up to date\n'
exit 0
